### ISSUE TITLE
Install problem on 3.4

### ISSUE THREAD

**Issue by andresayang** [gsingh7/SeisPos_Import#1]
Trying to install, and have this issue:
Couldn't load plugin 'seismic_importer' due to an error when calling its classFactory() method 
ImportError: cannot import name 'processing' from 'qgis' (C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\__init__.py) 

Maybe something is missing in my install ?

Thanks

**Comment by gsingh7** [comment]
Hi,
You would need to install the processing module of QGIS to be part of your installation. Please make sure that is available.
Thanks,
Gurpreet
